### ISSUE TITLE
Refactor fundraising section of sitetext.yml

### ISSUE THREAD

**Issue by corndogit** [SwanseaCompSci/tree-society-website#56]
**Is your feature request related to a problem? Please describe.**
This is a task mainly to make life easier for devs, but might require some frontend changes.
In sitetext.yml, charity fundraising information is stored in the `events` property as follows:
```yml
events:
  - title: "charity"
    desc: "<description>. **Our members raised a total of £xx!**"
    image: link/to/image.jpg
    alt: "charity"
```
Most site updates usually require looking through the description and manually changing the total raised, which is hard to maintain and can lead to error. 

**Describe the solution you'd like**
Add an extra property e.g. "funds_raised" amount:
```yml
events:
  - title: "charity"
    desc: "<description>"
    funds_raised: xx.xx # GBP
    image: link/to/image.jpg
    alt: "charity"
```
Then edit the HTML template to append the description string with "we raised a total of £<funds_raised>!"
Update the `desc` property for each charity so that it makes grammatical sense and remove any fundraising figures from it.

**Describe alternatives you've considered**
Separate charity information into a separate 'charities.yml' file, but the same could be done for other long sections of sitetext.yml and that goes outside of the scope for this ticket.
